# -*- coding: utf-8 -*-
"""ve_zphisher_logo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v2e95H7g7bNsZQ7Op01qhuOfAuLIjwen
"""

a = """
				  ______      _     _     _
				 |___  /     | |   (_)   | |
				    / / _ __ | |__  _ ___| |__   ___ _ __
				   / / | '_ \| '_ \| / __| '_ \ / _ \ '__|
				  / /__| |_) | | | | \__ \ | | |  __/ |
				 /_____| .__/|_| |_|_|___/_| |_|\___|_|
				       | |
                                       |_|
               """
b = """
F

		         ░▀▀█░█▀█░█░█░▀█▀░█▀▀░█░█░█▀▀░█▀▄
		         ░▄▀░░█▀▀░█▀█░░█░░▀▀█░█▀█░█▀▀░█▀▄
		         ░▀▀▀░▀░░░▀░▀░▀▀▀░▀▀▀░▀░▀░▀▀▀░▀░▀
"""
print(a)
print(b)